export { default as Hero } from "./landing/Hero/Hero";
export { default as Faq } from "./landing/Faq/Faq";
export { default as PreFooter } from "./landing/PreFooter/PreFooter";
export { default as Services } from "./landing/Services/Services";
export { default as Testimonial } from "./landing/Testimonial/Testimonial";
export { default as ContactUs } from "./ContactUs/ContactUs";
export { default as AboutUs } from "./AboutUs/AboutUs";
export { default as NewAboutUs } from "./AboutUs/NewAboutUs";
export { default as HeroForm } from "./landing/Hero/HeroForm";
